configform1:
  path: '/admin/config/system/site-information'
  defaults:
    _form: 'Drupal\config_module\Form\configform'
    _title: 'Custom Module for building config form'
  requirements:
    _permission: 'access content'